// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements. See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership. The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied. See the License for the
// specific language governing permissions and limitations
// under the License.

#include <cstring>
#include <utility>
#include <gtest/gtest.h>
#include "brpc/details/flatbuffers_impl.h"

namespace {

using brpc::flatbuffers::Message;
using brpc::flatbuffers::MessageBuilder;

// A minimal FlatBuffers table used only by these ownership tests. Keeping the
// type local avoids coupling this unit test to the RPC benchmark example or to
// code generated by a particular flatc version.
struct TestMessageBuilder;

struct TestMessage FLATBUFFERS_FINAL_CLASS
    : private ::flatbuffers::Table {
    typedef TestMessageBuilder Builder;

    enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
        VT_OPCODE = 4,
        VT_ECHO_ATTACHMENT = 6,
        VT_ATTACHMENT_SIZE = 8,
        VT_REQUEST_ID = 10,
        VT_RESERVED = 12,
        VT_MESSAGE = 14
    };

    int32_t opcode() const {
        return GetField<int32_t>(VT_OPCODE, 0);
    }

    int32_t echo_attachment() const {
        return GetField<int32_t>(VT_ECHO_ATTACHMENT, 0);
    }

    int64_t attachment_size() const {
        return GetField<int64_t>(VT_ATTACHMENT_SIZE, 0);
    }

    int64_t request_id() const {
        return GetField<int64_t>(VT_REQUEST_ID, 0);
    }

    int64_t reserved() const {
        return GetField<int64_t>(VT_RESERVED, 0);
    }

    const ::flatbuffers::String* message() const {
        return GetPointer<const ::flatbuffers::String*>(VT_MESSAGE);
    }

    template <bool B = false>
    bool Verify(::flatbuffers::VerifierTemplate<B>& verifier) const {
        return VerifyTableStart(verifier) &&
               VerifyField<int32_t>(verifier, VT_OPCODE, 4) &&
               VerifyField<int32_t>(
                   verifier, VT_ECHO_ATTACHMENT, 4) &&
               VerifyField<int64_t>(
                   verifier, VT_ATTACHMENT_SIZE, 8) &&
               VerifyField<int64_t>(verifier, VT_REQUEST_ID, 8) &&
               VerifyField<int64_t>(verifier, VT_RESERVED, 8) &&
               VerifyOffset(verifier, VT_MESSAGE) &&
               verifier.VerifyString(message()) &&
               verifier.EndTable();
    }
};

struct TestMessageBuilder {
    explicit TestMessageBuilder(
        ::flatbuffers::FlatBufferBuilder& builder)
        : builder_(builder), start_(builder_.StartTable()) {}

    void add_opcode(int32_t value) {
        builder_.AddElement<int32_t>(
            TestMessage::VT_OPCODE, value, 0);
    }

    void add_echo_attachment(int32_t value) {
        builder_.AddElement<int32_t>(
            TestMessage::VT_ECHO_ATTACHMENT, value, 0);
    }

    void add_attachment_size(int64_t value) {
        builder_.AddElement<int64_t>(
            TestMessage::VT_ATTACHMENT_SIZE, value, 0);
    }

    void add_request_id(int64_t value) {
        builder_.AddElement<int64_t>(
            TestMessage::VT_REQUEST_ID, value, 0);
    }

    void add_reserved(int64_t value) {
        builder_.AddElement<int64_t>(
            TestMessage::VT_RESERVED, value, 0);
    }

    void add_message(
        ::flatbuffers::Offset<::flatbuffers::String> value) {
        builder_.AddOffset(TestMessage::VT_MESSAGE, value);
    }

    ::flatbuffers::Offset<TestMessage> Finish() {
        return ::flatbuffers::Offset<TestMessage>(
            builder_.EndTable(start_));
    }

private:
    ::flatbuffers::FlatBufferBuilder& builder_;
    ::flatbuffers::uoffset_t start_;
};

::flatbuffers::Offset<TestMessage> CreateTestMessage(
    ::flatbuffers::FlatBufferBuilder& builder,
    int32_t opcode,
    int32_t echo_attachment,
    int64_t attachment_size,
    int64_t request_id,
    int64_t reserved,
    ::flatbuffers::Offset<::flatbuffers::String> message) {
    TestMessageBuilder result(builder);
    result.add_reserved(reserved);
    result.add_request_id(request_id);
    result.add_attachment_size(attachment_size);
    result.add_message(message);
    result.add_echo_attachment(echo_attachment);
    result.add_opcode(opcode);
    return result.Finish();
}

Message BuildRequest(const char* value) {
    MessageBuilder builder;
    const auto text = builder.CreateString(value);
    const auto root = CreateTestMessage(
        builder, 7, 1, 64, 123, 9, text);
    builder.Finish(root);
    return builder.ReleaseMessage();
}

TEST(FlatBuffersMessageTest, BuilderMoveConstructorPreservesBuffer) {
    MessageBuilder source;
    const auto text = source.CreateString("builder move constructor");
    const auto root = CreateTestMessage(
        source, 7, 1, 64, 123, 9, text);
    source.Finish(root);

    MessageBuilder target(std::move(source));
    Message message = target.ReleaseMessage();

    ASSERT_TRUE(message.Verify<TestMessage>());
    ASSERT_NE(nullptr, message.GetRoot<TestMessage>()->message());
    EXPECT_EQ("builder move constructor",
              message.GetRoot<TestMessage>()->message()->str());
}

TEST(FlatBuffersMessageTest, BuilderMoveAssignmentReplacesBuffer) {
    MessageBuilder target;
    const auto old_text = target.CreateString("old builder");
    const auto old_root = CreateTestMessage(
        target, 1, 0, 8, 10, 0, old_text);
    target.Finish(old_root);

    MessageBuilder source;
    const auto new_text = source.CreateString("replacement builder");
    const auto new_root = CreateTestMessage(
        source, 7, 1, 64, 123, 9, new_text);
    source.Finish(new_root);

    target = std::move(source);
    Message message = target.ReleaseMessage();

    ASSERT_TRUE(message.Verify<TestMessage>());
    const auto* result = message.GetRoot<TestMessage>();
    EXPECT_EQ(7, result->opcode());
    ASSERT_NE(nullptr, result->message());
    EXPECT_EQ("replacement builder", result->message()->str());
}

TEST(FlatBuffersMessageTest, ReleasedMessageSurvivesBuilderDestruction) {
    Message message = BuildRequest("hello");
    ASSERT_TRUE(message.Verify<TestMessage>());
    const auto* root = message.GetRoot<TestMessage>();
    EXPECT_EQ(7, root->opcode());
    EXPECT_EQ(1, root->echo_attachment());
    EXPECT_EQ(64, root->attachment_size());
    EXPECT_EQ(123, root->request_id());
    EXPECT_EQ(9, root->reserved());
    ASSERT_NE(nullptr, root->message());
    EXPECT_EQ("hello", root->message()->str());
}

TEST(FlatBuffersMessageTest, MoveConstructorPreservesBuffer) {
    Message source = BuildRequest("move constructor");
    const auto* data = source.data();
    const auto size = source.size();
    Message target(std::move(source));
    EXPECT_EQ(data, target.data());
    EXPECT_EQ(size, target.size());
    EXPECT_EQ(0u, source.size());
    source.Clear();
    ASSERT_TRUE(target.Verify<TestMessage>());
    ASSERT_NE(nullptr, target.GetRoot<TestMessage>()->message());
    EXPECT_EQ("move constructor",
              target.GetRoot<TestMessage>()->message()->str());
}

TEST(FlatBuffersMessageTest, MoveAssignmentReplacesExistingMessage) {
    Message target = BuildRequest("old contents");
    const uint8_t* data = nullptr;
    size_t size = 0;
    {
        Message source = BuildRequest("replacement");
        data = source.data();
        size = source.size();
        target = std::move(source);
        EXPECT_EQ(0u, source.size());
    }
    EXPECT_EQ(data, target.data());
    EXPECT_EQ(size, target.size());
    ASSERT_TRUE(target.Verify<TestMessage>());
    ASSERT_NE(nullptr, target.GetRoot<TestMessage>()->message());
    EXPECT_EQ("replacement",
              target.GetRoot<TestMessage>()->message()->str());
}

TEST(FlatBuffersMessageTest, RejectsCorruptRootOffset) {
    Message message = BuildRequest("corrupt");
    ASSERT_TRUE(message.Verify<TestMessage>());
    ASSERT_GE(message.size(), sizeof(::flatbuffers::uoffset_t));
    std::memset(message.mutable_data(), 0xff,
                sizeof(::flatbuffers::uoffset_t));
    EXPECT_FALSE(message.Verify<TestMessage>());
}

}  // namespace
